name: Auto Update Sitemap and Ping Google

on:
  push:
    branches:
      - main  # change to "master" if your repo uses master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          
          # Add homepage
          echo "  <url><loc>https://www.skill2job.site/</loc><lastmod>$(date +%Y-%m-%d)</lastmod></url>" >> sitemap.xml
          
          # Loop through all folders with index.html
          for dir in */; do
            if [ -f "$dir/index.html" ]; then
              echo "  <url><loc>https://www.skill2job.site/${dir%/}/</loc><lastmod>$(date +%Y-%m-%d)</lastmod></url>" >> sitemap.xml
            fi
          done
          
          echo '</urlset>' >> sitemap.xml

      - name: Commit sitemap
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap" || echo "No changes to commit"
          git push

      - name: Ping Google
        run: |
          curl "https://www.google.com/ping?sitemap=https://www.skill2job.site/sitemap.xml"
